version: '3.4'


services:
 api_translator:
   build:
     context: api
   image: ${REGISTRY}/api:${IMAGE_TAG}
   ports:
     - 8080:8080
   networks:
     - internal
     - public
   env_file: ./.env/.env_dev
   deploy:
     mode: replicated
     replicas: 1
     restart_policy:
       condition: on-failure
       delay: 10s
     update_config:
       parallelism: 1
       delay: 10s
       monitor: 10s
       order: start-first
       failure_action: rollback


networks:
 public:
   external:
     name: public
 internal:  
  



